name: Deploy S3 Bucket

on: [push, workflow_dispatch]

env:
  AWS_REGION: us-east-1                   # set this to your preferred AWS region, e.g. us-west-1
        
jobs:
  aws_s3:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # no need to set the GitHub Secret as it is automatically set by GitHub.
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::357171604946:role/gh-actions-role
          aws-region: ${{ env.AWS_REGION }}
      - name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: create-s3-bucket
          template: s3.yaml

# https://github.com/aws-actions/aws-cloudformation-github-deploy
# https://github.com/github/super-linter
