name: Deploy S3 Bucket

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: us-east-1                   # set this to your preferred AWS region, e.g. us-west-1
        
jobs:
  aws_s3:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    outputs:
      env-name: ${{ steps.env-name.outputs.environment }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Run Super-Linter
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: main
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::357171604946:role/gh-actions-role
          aws-region: ${{ env.AWS_REGION }}
      - name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@master
        with:
          name: create-s3-bucket
          template: s3.yaml

# https://github.com/aws-actions/aws-cloudformation-github-deploy
